from django.urls import path

from . import views


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("properties/", views.PropertyListView.as_view(), name="property_list"),
    path("properties/new/", views.property_create, name="property_create"),
    path("properties/<int:pk>/", views.property_detail, name="property_detail"),
    path("properties/<int:pk>/edit/", views.property_update, name="property_update"),
    path("units/new/", views.unit_create, name="unit_create"),
    path("units/<int:pk>/", views.unit_detail, name="unit_detail"),
    path("units/<int:pk>/mietbescheinigung/", views.unit_mietbescheinigung, name="unit_mietbescheinigung"),
    path("units/<int:pk>/edit/", views.unit_update, name="unit_update"),
    path("units/<int:pk>/administration/", views.unit_administration_update, name="unit_administration_update"),
    path("units/<int:pk>/change-tenant/", views.unit_change_tenant, name="unit_change_tenant"),
    path("tenants/", views.tenant_list, name="tenant_list"),
    path("tenants/new/", views.TenantCreateView.as_view(), name="tenant_create"),
    path("tenants/<int:pk>/edit/", views.tenant_update, name="tenant_update"),
    path("leases/new/", views.lease_create, name="lease_create"),
    path("leases/<int:pk>/people/", views.lease_people_update, name="lease_people_update"),
    path("rent-periods/new/", views.rent_period_create, name="rent_period_create"),
    path("rent-periods/<int:pk>/edit/", views.rent_period_update, name="rent_period_update"),
    path("rent-periods/<int:pk>/delete/", views.rent_period_delete, name="rent_period_delete"),
    path("snapshots/new/", views.AnnualPropertySnapshotCreateView.as_view(), name="snapshot_create"),
    path("snapshots/<int:pk>/edit/", views.AnnualPropertySnapshotUpdateView.as_view(), name="snapshot_update"),
    path("costs/new/", views.AnnualPropertyCostCreateView.as_view(), name="cost_create"),
    path("loans/", views.loan_list, name="loan_list"),
    path("loans/new/", views.loan_create, name="loan_create"),
    path("loans/<int:pk>/edit/", views.loan_update, name="loan_update"),
    path("loan-snapshots/new/", views.loan_snapshot_create, name="loan_snapshot_create"),
    path("loan-snapshots/<int:pk>/edit/", views.loan_snapshot_update, name="loan_snapshot_update"),
    path("potential-deals/", views.potential_deal_list, name="potential_deal_list"),
    path("potential-deals/new/", views.potential_deal_create, name="potential_deal_create"),
    path("potential-deals/<int:pk>/", views.potential_deal_detail, name="potential_deal_detail"),
    path("potential-deals/<int:pk>/edit/", views.potential_deal_update, name="potential_deal_update"),
    path("potential-deals/<int:pk>/optimizer/", views.potential_deal_optimizer, name="potential_deal_optimizer"),
    path("potential-deals/<int:deal_pk>/scenarios/new/", views.potential_scenario_create, name="potential_scenario_create"),
    path("potential-deals/scenarios/<int:pk>/edit/", views.potential_scenario_update, name="potential_scenario_update"),
    path("potential-deals/scenarios/<int:pk>/delete/", views.potential_scenario_delete, name="potential_scenario_delete"),
    path("reference/", views.reference_page, name="reference"),
    path("import/", views.import_workbook, name="import_workbook"),
    path("exports/", views.exports_page, name="exports"),
    path("backup/", views.backup_page, name="backup"),
    path("settings/", views.settings_page, name="settings"),
    path("exports/bank-financing/current.pdf", views.export_bank_financing_pdf, name="export_bank_financing_pdf"),
    path("exports/bank-financing/current.xlsx", views.export_bank_financing_excel, name="export_bank_financing_excel"),
    path("exports/files/<str:file_name>", views.export_file, name="export_file"),
    path("backups/create/", views.create_backup, name="create_backup"),
    path("backups/restore/", views.restore_backup, name="restore_backup"),
]
