# Generated by Django 5.2.14 on 2026-05-18 13:33

from decimal import Decimal
from datetime import date
from django.db import migrations, models


def backfill_defaults(apps, schema_editor):
    Loan = apps.get_model("portfolio", "Loan")
    AnnualLoanSnapshot = apps.get_model("portfolio", "AnnualLoanSnapshot")
    db_alias = schema_editor.connection.alias
    for loan in Loan.objects.using(db_alias).all():
        snapshot = (
            AnnualLoanSnapshot.objects.using(db_alias)
            .filter(loan=loan, year=2026)
            .first()
            or AnnualLoanSnapshot.objects.using(db_alias).filter(loan=loan).order_by("-year").first()
        )
        if snapshot:
            loan.default_interest_rate = snapshot.interest_rate
            loan.default_monthly_payment = snapshot.monthly_payment
        if not loan.start_date:
            first_snapshot = AnnualLoanSnapshot.objects.using(db_alias).filter(loan=loan).order_by("year").first()
            if first_snapshot:
                loan.start_date = date(first_snapshot.year, 1, 1)
        loan.save(update_fields=["default_interest_rate", "default_monthly_payment", "start_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_loan_amounts_total_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='loan',
            name='default_monthly_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunPython(backfill_defaults, migrations.RunPython.noop),
    ]
